### ISSUE TITLE
Migrations are broken - duplicate names

### ISSUE THREAD

**Issue by ybakos** [osu-cascades/intouch-web#14]
rails db:migrate
rails aborted!
ActiveRecord::DuplicateMigrationNameError:

Multiple migrations have the name CreateUsers.

/Users/yongbakos/.rvm/gems/ruby-2.4.1@intouch-web/gems/activerecord-5.1.4/lib/active_record/migration.rb:1254:in `validate'
/Users/yongbakos/.rvm/gems/ruby-2.4.1@intouch-web/gems/activerecord-5.1.4/lib/active_record/migration.rb:1123:in `initialize'
/Users/yongbakos/.rvm/gems/ruby-2.4.1@intouch-web/gems/activerecord-5.1.4/lib/active_record/migration.rb:1007:in `new'
/Users/yongbakos/.rvm/gems/ruby-2.4.1@intouch-web/gems/activerecord-5.1.4/lib/active_record/migration.rb:1007:in `up'
/Users/yongbakos/.rvm/gems/ruby-2.4.1@intouch-web/gems/activerecord-5.1.4/lib/active_record/migration.rb:985:in `migrate'
/Users/yongbakos/.rvm/gems/ruby-2.4.1@intouch-web/gems/activerecord-5.1.4/lib/active_record/tasks/database_tasks.rb:171:in `migrate'
/Users/yongbakos/.rvm/gems/ruby-2.4.1@intouch-web/gems/activerecord-5.1.4/lib/active_record/railties/databases.rake:58:in `block (2 levels) in <top (required)>'
/Users/yongbakos/.rvm/gems/ruby-2.4.1@intouch-web/gems/railties-5.1.4/lib/rails/commands/rake/rake_command.rb:21:in `block in perform'
/Users/yongbakos/.rvm/gems/ruby-2.4.1@intouch-web/gems/railties-5.1.4/lib/rails/commands/rake/rake_command.rb:18:in `perform'
/Users/yongbakos/.rvm/gems/ruby-2.4.1@intouch-web/gems/railties-5.1.4/lib/rails/command.rb:46:in `invoke'
/Users/yongbakos/.rvm/gems/ruby-2.4.1@intouch-web/gems/railties-5.1.4/lib/rails/commands.rb:16:in `<top (required)>'
/Users/yongbakos/projects/intouch-web/bin/rails:9:in `require'
/Users/yongbakos/projects/intouch-web/bin/rails:9:in `<top (required)>'
/Users/yongbakos/.rvm/gems/ruby-2.4.1@intouch-web/gems/spring-2.0.2/lib/spring/client/rails.rb:28:in `load'
/Users/yongbakos/.rvm/gems/ruby-2.4.1@intouch-web/gems/spring-2.0.2/lib/spring/client/rails.rb:28:in `call'
/Users/yongbakos/.rvm/gems/ruby-2.4.1@intouch-web/gems/spring-2.0.2/lib/spring/client/command.rb:7:in `call'
/Users/yongbakos/.rvm/gems/ruby-2.4.1@intouch-web/gems/spring-2.0.2/lib/spring/client.rb:30:in `run'
/Users/yongbakos/.rvm/gems/ruby-2.4.1@intouch-web/gems/spring-2.0.2/bin/spring:49:in `<top (required)>'
/Users/yongbakos/.rvm/gems/ruby-2.4.1@intouch-web/gems/spring-2.0.2/lib/spring/binstub.rb:31:in `load'
/Users/yongbakos/.rvm/gems/ruby-2.4.1@intouch-web/gems/spring-2.0.2/lib/spring/binstub.rb:31:in `<top (required)>'
/Users/yongbakos/projects/intouch-web/bin/spring:15:in `require'
/Users/yongbakos/projects/intouch-web/bin/spring:15:in `<top (required)>'
bin/rails:3:in `load'
bin/rails:3:in `<main>'
Tasks: TOP => db:migrate
(See full trace by running task with --trace)

**Comment by gonzalky7** [comment]
Was this issue fixed @Aaronmb123

**Comment by ybakos** [comment]
@gonzalky7 Yes, it was.

**Comment by ybakos** [comment]
@Aaronmb123 Close this?

**Comment by gonzalky7** [comment]
Closing!!
